### ISSUE TITLE
Setup NGINX logs 

### ISSUE THREAD

**Issue by vincent-gou** [skenderidis/nap-dashboard#4]
Hi,

Could you provide an example  NGINX App Protect WAF config or client side config.
I was able to setup all components but nothing coming in grafana... All dashboards are empty.

I you have a way to test NGinx WAF enabled config to logstash then in Grafana it would be great.

If i test from nginx server to test syslog communication it works:

![image](https://user-images.githubusercontent.com/46958513/170285352-78af2569-796f-42eb-b5ae-72f6cdcabfaf.png)

![image](https://user-images.githubusercontent.com/46958513/170283705-1fdd269b-4231-4cf0-8617-191c40aec904.png)

Here my default nginx config
![image](https://user-images.githubusercontent.com/46958513/170284024-28404656-7d4f-4e3c-b922-98c6659ffd93.png)

Nginx log format:
![image](https://user-images.githubusercontent.com/46958513/170285148-7f4556be-67eb-49de-bc55-6e93ddb15f30.png)

Thanks

Vincent

**Comment by vincent-gou** [comment]
Adding following information in correct block permit syslog communication to logstash 

```
        app_protect_enable on;
        app_protect_security_log_enable on;
        app_protect_security_log "/etc/nginx/custom_log_format.json" syslog:server=<logstash_server_ip>:515;
```

Disabling selinux on Nginx App Protect server seems to permit syslog communication since it's blocked if selinux is activated.

**Comment by skenderidis** [comment]
Hi Vincent,

Sorry, I was on vacations and I missed the email/issue. let me know if you
need anything else. I am planning to add few more functionalities over the
next few days.
Again sorry.

Kostas
