### ISSUE TITLE
Syslog port: use a port > 1024

### ISSUE THREAD

**Issue by nergalex** [skenderidis/nap-dashboard#6]
Could you change syslog port with a port > 1024?

I got this issue:
`[WARN ][logstash.inputs.syslog ][main] syslog listener died {:protocol=>:udp, :address=>"0.0.0.0:515", :exception=>#<Errno::EACCES: Permission denied - bind(2) for "0.0.0.0" port 515>`

Fix: `docker-compose.yaml `

```
    ports:
      - 5144:5144
```

**Comment by skenderidis** [comment]
It makes sense. I will change it ASAP.

**Comment by nergalex** [comment]
Need also to modify `logstash.conf`: `input.syslog.port: 5144`

example:
```
input {
  syslog {
    port => 5144
    codec => plain {
      charset => "ISO-8859-1"
    }
  }
}
```
